module.exports = ({ env }) => [
  'strapi::logger',
  'strapi::errors',
  'strapi::security',
  {
    name: 'strapi::cors',
    config: {
      origin: [
        env('NEXT_PUBLIC_AUTH_URL', 'http://localhost:3003'),
        env('NEXT_PUBLIC_STOCK_URL', 'http://localhost:3001'),
        env('NEXT_PUBLIC_SALE_URL', 'http://localhost:3002'),
        env('NEXT_PUBLIC_WEB_USER_URL', 'http://localhost:3004'),
        env('NEXT_PUBLIC_CRM_URL', 'http://localhost:3005'),
        env('NEXT_PUBLIC_HR_URL', 'http://localhost:3006'),
        env('NEXT_PUBLIC_ACCOUNTS_URL', 'http://localhost:3007'),
        env('NEXT_PUBLIC_PAYROLL_URL', 'http://localhost:3008'),
        'http://localhost:3000',
        'http://localhost:3001',
        'http://localhost:3002',
        'http://localhost:3003',
        'http://localhost:3004',
        'http://localhost:3005',
        'http://localhost:3006',
        'http://localhost:3007',
        'http://localhost:3008',
        'http://127.0.0.1:3000',
        'http://127.0.0.1:3001',
        'http://127.0.0.1:3002',
        'http://127.0.0.1:3003',
        'http://127.0.0.1:3004',
        'http://127.0.0.1:3005',
        'http://127.0.0.1:3006',
        'http://127.0.0.1:3007',
        'http://127.0.0.1:3008',
      ],
      headers: [
        'Content-Type',
        'Authorization',
        'X-App-Name',
        'Origin',
        'Accept',
      ],
      methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
      keepHeaderOnError: true,
    },
  },
  'strapi::poweredBy',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
  'global::app-access-guard',
];
